/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SirensRouteImport } from './routes/sirens'
import { Route as RocketAttackRouteImport } from './routes/rocket-attack'
import { Route as ForcesRouteImport } from './routes/forces'
import { Route as EventsRouteImport } from './routes/events'
import { Route as IndexRouteImport } from './routes/index'

const SirensRoute = SirensRouteImport.update({
  id: '/sirens',
  path: '/sirens',
  getParentRoute: () => rootRouteImport,
} as any)
const RocketAttackRoute = RocketAttackRouteImport.update({
  id: '/rocket-attack',
  path: '/rocket-attack',
  getParentRoute: () => rootRouteImport,
} as any)
const ForcesRoute = ForcesRouteImport.update({
  id: '/forces',
  path: '/forces',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/forces': typeof ForcesRoute
  '/rocket-attack': typeof RocketAttackRoute
  '/sirens': typeof SirensRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/forces': typeof ForcesRoute
  '/rocket-attack': typeof RocketAttackRoute
  '/sirens': typeof SirensRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/forces': typeof ForcesRoute
  '/rocket-attack': typeof RocketAttackRoute
  '/sirens': typeof SirensRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/events' | '/forces' | '/rocket-attack' | '/sirens'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/events' | '/forces' | '/rocket-attack' | '/sirens'
  id: '__root__' | '/' | '/events' | '/forces' | '/rocket-attack' | '/sirens'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRoute: typeof EventsRoute
  ForcesRoute: typeof ForcesRoute
  RocketAttackRoute: typeof RocketAttackRoute
  SirensRoute: typeof SirensRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sirens': {
      id: '/sirens'
      path: '/sirens'
      fullPath: '/sirens'
      preLoaderRoute: typeof SirensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rocket-attack': {
      id: '/rocket-attack'
      path: '/rocket-attack'
      fullPath: '/rocket-attack'
      preLoaderRoute: typeof RocketAttackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forces': {
      id: '/forces'
      path: '/forces'
      fullPath: '/forces'
      preLoaderRoute: typeof ForcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRoute: EventsRoute,
  ForcesRoute: ForcesRoute,
  RocketAttackRoute: RocketAttackRoute,
  SirensRoute: SirensRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
